stages:
  data_ingestion:
    cmd: python src/sentimentAnalysis/pipeline/stage_01_data_ingestion.py
    deps:
      - src/sentimentAnalysis/pipeline/stage_01_data_ingestion.py
    outs:
      - artifacts/data_ingestion/IMDB_Dataset.csv

  data_preprocessing:
    cmd: python src/sentimentAnalysis/pipeline/stage_02_data_preprocessing.py
    deps:
      - artifacts/data_ingestion/IMDB_Dataset.csv
      - src/sentimentAnalysis/pipeline/stage_02_data_preprocessing.py
      - config/config.yaml
    # params:
    #   - data_preprocessing.max_words
    #   - data_preprocessing.max_sequence_length
    #   - data_preprocessing.train_test_split_ratio
    #   - data_preprocessing.random_state
    outs:
      - artifacts/data_preprocessing/X_train.csv
      - artifacts/data_preprocessing/X_test.csv
      - artifacts/data_preprocessing/train_data.csv
      - artifacts/data_preprocessing/test_data.csv

  model_training:
    cmd: python src/sentimentAnalysis/pipeline/stage_03_model_building.py
    deps:
      - artifacts/data_preprocessing/X_train.csv
      - artifacts/data_preprocessing/train_data.csv
      - src/sentimentAnalysis/pipeline/stage_03_model_building.py
      - params.yaml
    params:
      - model_config.n_estimators
      - model_config.max_depth
      - model_config.min_samples_split
      - model_config.min_samples_leaf
      - model_config.max_features
      - model_config.bootstrap
      - model_config.class_weight
      - model_config.random_state
    outs:
      - artifacts/model/model.joblib

  model_evaluation:
    cmd: python src/sentimentAnalysis/pipeline/stage_04_model_eval.py
    deps:
      - artifacts/model/model.joblib
      - artifacts/data_preprocessing/X_test.csv
      - artifacts/data_preprocessing/test_data.csv
      - src/sentimentAnalysis/pipeline/stage_04_model_eval.py
      - config/config.yaml 
    # params:
    #   - mlflow_config.mlflow_uri
    outs:
      - evaluation_scores.json
