model_config:
  input_dim: 10000
  output_dim: 1
  input_length: 200
  lstm_units: 128
  dropout_rate: 0.2
  optimizer: "adam"
  loss: "binary_crossentropy"
  metrics: ["accuracy"]
  epochs: 5
  batch_size: 32
  validation_split: 0.2