artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1lZNRzs4hNQS2F63SDmQb1t4LSasluA7s/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  # unzip: true
  unzip_dir: artifacts/data_ingestion

data_validation:
  expected_columns: ["review", "sentiment"]
  sentiment_values: ["positive", "negative"]

data_preprocessing:
  max_words: 5000
  max_sequence_length: 200
  train_test_split_ratio: 0.2
  random_state: 42
  train_data_path: "artifacts/IMDB_Dataset/train_data.csv"
  test_data_path: "artifacts/IMDB_Dataset/test_data.csv"